version: '3.1'
services:
  docker_postgres:
    container_name: docker_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
  docker_mongo:
    container_name: docker_mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongoroot
  docker_mysql:
    image: mysql:latest
    container_name: docker_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dockermysql
      MYSQL_DATABASE: dbmysql
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on: 
      - docker_mysql
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: docker_mysql
  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8082:8080