version: '3.1'
services:
  docker_mongo:
    container_name: docker_mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongoroot
  docker_mysql:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dockermysql
      MYSQL_DATABASE: dbmysql
      MYSQL_USER: dockermysql
      MYSQL_PASSWORD: dockermysql
    ports:
      - 3306:3306